use bevy::prelude::*;
use crate::facelet;
pub fn face_color(facelet:&facelet::Facelet)->Color{
    use facelet::Facelet::*;
    match facelet{
        Ufl|Uf|Ufr|Ul|U|Ur|Ubl|Ub|Ubr=>Color::Srgba(bevy::color::palettes::css::WHITE),
        Dbl|Db|Dbr|Dl|D|Dr|Dfl|Df|Dfr=>Color::Srgba(bevy::color::palettes::css::YELLOW),
        Fdl|Fd|Fdr|Fl|F|Fr|Ful|Fu|Fur=>Color::Srgba(bevy::color::palettes::css::RED),
        Bdr|Bd|Bdl|Br|B|Bl|Bur|Bu|Bul=>Color::Srgba(bevy::color::palettes::css::ORANGE),
        Ldb|Ld|Ldf|Lb|L|Lf|Lub|Lu|Luf=>Color::Srgba(bevy::color::palettes::css::GREEN),
        Rdf|Rd|Rdb|Rf|R|Rb|Ruf|Ru|Rub=>Color::Srgba(bevy::color::palettes::css::BLUE),
    }
}
pub fn face_number(facelet:&facelet::Facelet)->u8{
    use facelet::Facelet::*;
    match facelet{
        Ufl=>16,
        Uf=>1,
        Ufr=>9,
        Ul=>2,
        U=>4,
        Ur=>5,
        Ubl=>0,
        Ub=>11,
        Ubr=>8,
        Dbl=>13,
        Db=>17,
        Dbr=>0,
        Dl=>15,
        D=>4,
        Dr=>3,
        Dfl=>14,
        Df=>10,
        Dfr=>6,
        Fdl=>8,
        Fd=>11,
        Fdr=>12,
        Fl=>12,
        F=>0,
        Fr=>5,
        Ful=>1,
        Fu=>2,
        Fur=>9,
        Bdr=>8,
        Bd=>17,
        Bdl=>9,
        Br=>10,
        B=>0,
        Bl=>6,
        Bur=>13,
        Bu=>15,
        Bul=>4,
        Ldb=>13,
        Ld=>5,
        Ldf=>14,
        Lb=>2,
        L=>0,
        Lf=>16,
        Lub=>7,
        Lu=>11,
        Luf=>4,
        Rdf=>4,
        Rd=>15,
        Rdb=>14,
        Rf=>7,
        R=>13,
        Rb=>11,
        Ruf=>0,
        Ru=>10,
        Rub=>3,
    }
}
